import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Banner } from '../components/Banner'
import { NavBar } from '../components/NavBar'
import { WordPrompt } from '../components/WordPrompt'
import { ColourPalette } from '../components/ColourPalette'
import RandomImage from '../components/RandomImage/randomimage'


const inter = Inter({ subsets: ['latin'] })


export default function Home() {

    return (
        <>
            <Head>
                <title>Artner - Home</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.main}>
                <NavBar />
                <Banner
                    bannerHeading="Art Inspiration Generator"
                    bannerDescription="Lorem ipsum dolor sit amet consectetur. Id non at adipiscing sed morbi vel sit urna lectus. Eget lacus morbi facilisis mattis enim. Nisi vehicula orci praesent morbi cras placerat diam. Magna egestas vitae imperdiet eget sem duis molestie." />


                <ColourPalette />
                <WordPrompt />
                <RandomImage/>
            </div>


        </>
    )
}
